accounts:
  bili: []
  dy: []
  ks: []
  wb: []
  xhs:
  - cookies: NID=527=TSkgoK0UgjQcfgNaW4zrvKz0n-ToTdP0Ql_NdwYk6uZnRTZfZCggYqby6lOadK9thsOkTdzZA0OLWAAYL2kevwtwu07S4fnGxj8FUW0Ry7mGyIV69V4DWcu48D-n_mSUmhVkYLKz-kFCP0RBnZTFHLAfCrzGQtqk8qiVWB_Jhw25aptklPqwaFF3Y7DOzErRqoT0zyofgtOHz151jVdH;gid=yjKqS8jiyyAiyjKqS8jfi1lUy8T7T7ihx2fFkhIKMjfFC4q81Wq6Ty888j4JY848iSKfWW20;xsecappid=xhs-pc-web;abRequestId=0d04f442-6d09-50fe-8704-b01fdf993f8a;a1=19b9c681430om3vqgpurckvewakfvmvqu8aiuhdwh30000316385;webId=4e99ee8da5f0fc0066c5febd71882ccf;websectiga=9730ffafd96f2d09dc024760e253af6ab1feb0002827740b95a255ddf6847fc8;acw_tc=0a00d2d717678578562876951ede9136f69c592e86d08a28a3b95d6cf71b4f;webBuild=5.6.5;loadts=1767857857513;acw_tc=0ad598a717678578598291198e4a3818d6e6d58e04eb4dc1473c00dd5bd2c3;web_session=040069b30294e6d476fdb1166a3b4b238d8cfa;id_token=VjEAACzRlggfmZMYlBllGgxcuLcLlYFFphyandhk9SitQn+ufKs5sZCDMD6A+1mLwa/RJp/7VFDyml2IHTe/QR/+Q7Tzjly4OQGB7fiI2jR764EY4202jzCuChE83zUIazEHFR9x;unread={%22ub%22:%22695f49cc00000000220224c3%22%2C%22ue%22:%226950827c000000001e02493f%22%2C%22uc%22:19}
    error_count: 0
    id: 7cb499e4
    name: XHS_Scan_20260108_153806
    notes: Created via Scan Login
    request_count: 0
    status: active
    success_count: 0
